services:

  sageattention-wheel-cu13:
    container_name: sageattention-wheel-cu13
    image: snw35/sageattention-wheel:cu13
    volumes:
      - type: bind
        source: ./wheelhouse
        target: /home/ubuntu/wheelhouse
    restart: no
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  sageattention-wheel-cu12:
    container_name: sageattention-wheel-cu12
    image: snw35/sageattention-wheel:cu12
    volumes:
      - type: bind
        source: ./wheelhouse
        target: /home/ubuntu/wheelhouse
    restart: no
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
